# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TajoIdProtos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TajoIdProtos.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12TajoIdProtos.proto\"\'\n\x0cQueryIdProto\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0b\n\x03seq\x18\x02 \x02(\x05\"C\n\x15\x45xecutionBlockIdProto\x12\x1e\n\x07queryId\x18\x01 \x02(\x0b\x32\r.QueryIdProto\x12\n\n\x02id\x18\x02 \x02(\x05\"K\n\x0bTaskIdProto\x12\x30\n\x10\x65xecutionBlockId\x18\x01 \x02(\x0b\x32\x16.ExecutionBlockIdProto\x12\n\n\x02id\x18\x02 \x02(\x05\">\n\x12TaskAttemptIdProto\x12\x1c\n\x06taskId\x18\x01 \x02(\x0b\x32\x0c.TaskIdProto\x12\n\n\x02id\x18\x02 \x02(\x05\"\x1c\n\x0eSessionIdProto\x12\n\n\x02id\x18\x01 \x02(\tB%\n\x0forg.apache.tajoB\x0cTajoIdProtos\x88\x01\x00\xa0\x01\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_QUERYIDPROTO = _descriptor.Descriptor(
  name='QueryIdProto',
  full_name='QueryIdProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='QueryIdProto.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='QueryIdProto.seq', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=61,
)


_EXECUTIONBLOCKIDPROTO = _descriptor.Descriptor(
  name='ExecutionBlockIdProto',
  full_name='ExecutionBlockIdProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queryId', full_name='ExecutionBlockIdProto.queryId', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='ExecutionBlockIdProto.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=130,
)


_TASKIDPROTO = _descriptor.Descriptor(
  name='TaskIdProto',
  full_name='TaskIdProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='executionBlockId', full_name='TaskIdProto.executionBlockId', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='TaskIdProto.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=207,
)


_TASKATTEMPTIDPROTO = _descriptor.Descriptor(
  name='TaskAttemptIdProto',
  full_name='TaskAttemptIdProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='TaskAttemptIdProto.taskId', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='TaskAttemptIdProto.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=271,
)


_SESSIONIDPROTO = _descriptor.Descriptor(
  name='SessionIdProto',
  full_name='SessionIdProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SessionIdProto.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=301,
)

_EXECUTIONBLOCKIDPROTO.fields_by_name['queryId'].message_type = _QUERYIDPROTO
_TASKIDPROTO.fields_by_name['executionBlockId'].message_type = _EXECUTIONBLOCKIDPROTO
_TASKATTEMPTIDPROTO.fields_by_name['taskId'].message_type = _TASKIDPROTO
DESCRIPTOR.message_types_by_name['QueryIdProto'] = _QUERYIDPROTO
DESCRIPTOR.message_types_by_name['ExecutionBlockIdProto'] = _EXECUTIONBLOCKIDPROTO
DESCRIPTOR.message_types_by_name['TaskIdProto'] = _TASKIDPROTO
DESCRIPTOR.message_types_by_name['TaskAttemptIdProto'] = _TASKATTEMPTIDPROTO
DESCRIPTOR.message_types_by_name['SessionIdProto'] = _SESSIONIDPROTO

QueryIdProto = _reflection.GeneratedProtocolMessageType('QueryIdProto', (_message.Message,), dict(
  DESCRIPTOR = _QUERYIDPROTO,
  __module__ = 'TajoIdProtos_pb2'
  # @@protoc_insertion_point(class_scope:QueryIdProto)
  ))
_sym_db.RegisterMessage(QueryIdProto)

ExecutionBlockIdProto = _reflection.GeneratedProtocolMessageType('ExecutionBlockIdProto', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTIONBLOCKIDPROTO,
  __module__ = 'TajoIdProtos_pb2'
  # @@protoc_insertion_point(class_scope:ExecutionBlockIdProto)
  ))
_sym_db.RegisterMessage(ExecutionBlockIdProto)

TaskIdProto = _reflection.GeneratedProtocolMessageType('TaskIdProto', (_message.Message,), dict(
  DESCRIPTOR = _TASKIDPROTO,
  __module__ = 'TajoIdProtos_pb2'
  # @@protoc_insertion_point(class_scope:TaskIdProto)
  ))
_sym_db.RegisterMessage(TaskIdProto)

TaskAttemptIdProto = _reflection.GeneratedProtocolMessageType('TaskAttemptIdProto', (_message.Message,), dict(
  DESCRIPTOR = _TASKATTEMPTIDPROTO,
  __module__ = 'TajoIdProtos_pb2'
  # @@protoc_insertion_point(class_scope:TaskAttemptIdProto)
  ))
_sym_db.RegisterMessage(TaskAttemptIdProto)

SessionIdProto = _reflection.GeneratedProtocolMessageType('SessionIdProto', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONIDPROTO,
  __module__ = 'TajoIdProtos_pb2'
  # @@protoc_insertion_point(class_scope:SessionIdProto)
  ))
_sym_db.RegisterMessage(SessionIdProto)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\017org.apache.tajoB\014TajoIdProtos\210\001\000\240\001\001'))
import abc
from grpc.early_adopter import implementations
from grpc.framework.alpha import utilities
# @@protoc_insertion_point(module_scope)
